#!/bin/bash
#

dockerfile=$1
if [ "$dockerfile" == "" ]; then
    echo "Usage $0 <name-of-dockerfile> [branch] [fresh]"
    exit -1
fi

branch=$2
if [ "$branch" == "" ]; then
    echo "No branch argument (will checkout master)"
    branch="master"
fi

name=`basename $dockerfile`
cachearg=''
if [ "$3" == "fresh" ]; then
    echo 'Building a fresh image using --no-cache'
    cachearg='--no-cache'
fi
docker build $cachearg --build-arg branch=$branch -t rosie:$name -f $dockerfile . 

