---- -*- Mode: Lua; -*-                                                                           
----
---- cmdlinesniff.lua      sniff test for the CLI
----
---- © Copyright IBM Corporation 2016.
---- LICENSE: MIT License (https://opensource.org/licenses/mit-license.html)
---- AUTHOR: Jamie A. Jennings

infilename = "/tmp/rosietestinputfile"

rosie = ROSIE_HOME .. "/run"
input = [[
#
# This file is automatically generated.
#
search nc.rr.com
nameserver 10.0.1.1
nameserver 2606:a000:1120:8152:2f7:6fff:fed4:dc1f
/usr/share/bin/foo
jjennings@us.ibm.com
]]

f, msg = io.open(infilename, "w")
if (not f) then
   error("Could not create the input file for this test: " .. tostring(msg))
end
f:write(input)
f:close()

print("Input file (" .. infilename .. ") created successfully")

function run(expression, grep_flag)
   local grep = (grep_flag and " -grep") or ""
   local cmd = rosie .. grep .. " '" .. expression .. "' " .. infilename
   local p, msg = io.popen(cmd)
   if (not p) then error("Could not start rosie: " .. msg); end
   local output = p:read("*a")
   p:close()
   print(output)
end

run("basic.matchall")
run("common.word")
run("common.word", true)
run("common.word basic.network_patterns")
run("common.number", true)
