#!/usr/bin/env bash

pushd . > /dev/null
SCRIPT_PATH="${BASH_SOURCE[0]}";
if ([ -h "${SCRIPT_PATH}" ]) then
  while([ -h "${SCRIPT_PATH}" ]) do cd `dirname "$SCRIPT_PATH"`; SCRIPT_PATH=`readlink "${SCRIPT_PATH}"`; done
fi
cd `dirname ${SCRIPT_PATH}` > /dev/null
SCRIPT_PATH=`pwd`;
popd  > /dev/null

I=""
DEV="false"

#
# -D is an 'undocumented' command line option that launches Rosie in development mode
#
if [[ "$1" = "-D" ]]; then
   I="-i"
   DEV="true"
   shift
fi

if ([ -x $SCRIPT_PATH/bin/lua ]) then
   ROSIE_LUA_PATH=$SCRIPT_PATH;
   elif ([ -x $ROSIE_HOME/bin/lua ]) then
	ROSIE_LUA_PATH=$ROSIE_HOME;
   else
       echo "Cannot find Rosie install directory:"
       echo "  Rosie not found in $SCRIPT_PATH (the directory in which this script resides)"
       echo "  Rosie not found in $ROSIE_HOME (the value of environment variable 'ROSIE_HOME')"
       echo "Please either build Rosie, or set the environment variable 'ROSIE_HOME' as needed."
       exit -1
fi

/usr/bin/env ROSIE_HOME=$ROSIE_HOME HOSTNAME=$HOSTNAME HOSTTYPE=$HOSTTYPE OSTYPE=$OSTYPE $ROSIE_LUA_PATH/bin/lua $I -e "ROSIE_HOME=\"$ROSIE_LUA_PATH\"; SCRIPTNAME=\"$0\"; ROSIE_DEV=$DEV" $ROSIE_LUA_PATH/src/run.lua "$@"
