.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "ROSIE" "1" "March 2018" "The Rosie Project" ""
.
.SH "NAME"
\fBrosie\fR \- Rosie Pattern Engine (Rosie Pattern Language)
.
.SH "SYNOPSIS"
\fBrosie\fR [global\-options] command [command\-options] pattern\-expression [file1 [file2 \.\.\.]]
.
.SH "DESCRIPTION"
\fBRosie\fR searches all given input files for lines that match a pattern\. The pattern language is similar to regular expressions, but more powerful\. Also, a set of predefined (named) patterns are provided\. The pattern library is extensible\. Rosie patterns are written in \fBRosie Pattern Language (RPL)\fR\.
.
.P
A shared library, \fBlibrosie\fR, provides a programmatic interface to rosie in C, Go, Python, and other languages that support \fBlibffi\fR\. \fBRosie\fR can be used for data mining on large data sets, or for the kind of smaller tasks that Unix \fBgrep\fR and other regex tools are used for\. The output can be plain text, like \fBgrep\fR produces, or can be structured JSON, in the form of a parse tree\. A number of other output options are available (see below)\.
.
.SH "LANGUAGE REFERENCE"
The RPL Language Reference may be found via the Rosie home page \fIhttp://rosie\-lang\.org\fR (news, docs, and more)\.
.
.SH "COMMANDS"
The primary commands are \fBmatch\fR and \fBgrep\fR\. Help for a command is obtained using the \fB\-h\fR option (see below)\. General help is available with the \fBhelp\fR command\.
.
.TP
\fBconfig\fR
Print the configuration of the Rosie installation, including build information if available\.
.
.TP
\fBexpand\fR \fIexp\fR
Expands a \fBpattern expression\fR entered on the command line\. Output is: (1) the expression as entered (which will show any shell expansions or substitutions); (2) the parsed expression; (3) what the expression means at top level, where a bare expression is a tokenized expression; and (4) the result after any macro expansions\.
.
.TP
\fBgrep\fR \fIexp\fR [file1 \.\.\.]
In the style of grep, match the given \fBpattern\fR against lines in the given input files (or the standard input)\. In this mode, the pattern may match anywhere within a line, and all matches within a line are found\. The default output form in this mode is to print the entire line for all lines that match\.
.
.TP
\fBhelp\fR
Print help text\.
.
.TP
\fBlist\fR [name[\.name]]
List the available patterns from the library whose name matches \fBname\fR\. To list all the names in an imported package, use \fBlist pkgname\.*\fR\.
.
.TP
\fBmatch\fR \fIexp\fR [file1 \.\.\.]
Match the given \fBpattern\fR against lines in the given input files (or the standard input)\. Patterns in RPL begin at the start of the input line\. See the \fBgrep\fR command for behavior that is more like that utility\.
.
.TP
\fBrepl\fR
Enter the read\-eval\-print loop for interactive development and testing of patterns
.
.TP
\fBtest\fR \fIfile1\fR [file2\.\.\.]
Execute the unit tests embedded within the listed rpl files\.
.
.TP
\fBtrace\fR \fIexp\fR [file1 \.\.\.]
Perform a match, but generate a trace listing of all the steps performed in the matching process\. This can be quite a lot of output\.
.
.TP
\fBversion\fR
Print the Rosie version and exit\.
.
.SH "GLOBAL OPTIONS"
.
.TP
\fB\-\-colors\fR \fIcolorspecs\fR
Specify a set of colors and font attributes, each associated with a pattern name\. The format of \fBcolorspecs\fR is a colon\-separated list of \fBname=spec\fR, where:
.
.IP
\fBspec\fR is a semi\-colon separated list of ANSI (SGR) color and font attributes\. Colors may be specified by name or integer code\. Attributes include bold, underline, and others\.
.
.IP
\fBname\fR can be \fB*\fR for a global default; \fBpkgname\.*\fR for a package default; \fBlocalname\fR to match a name exactly, without a prefix; or \fBpkgname\.localname\fR to match an imported name exactly\.
.
.TP
\fB\-f, \-\-file\fR \fIfile\fR
Load a file of rpl code\. This option may be repeated\.
.
.TP
\fB\-\-libpath\fR \fIpaths\fR
Set the rosie \fBlibpath\fR, which is a colon\-separated list of directories to search, in order, for imported packages\. The value is a colon\-separated string\. When the \fBlibpath\fR is not set by the user, Rosie looks for imported packages in the installation directory, at \fBROSIE_LIBDIR\fR (the value of which can be seen using the \fBrosie config\fR command)\.
.
.IP
\fBImportant note:\fR If you set the libpath, you must explicitly include the standard library if you want Rosie to include the standard library in its search\. A \fBlibpath\fR set on the command line takes precedence over one set in an initialization file\.
.
.TP
\fB\-\-norcfile\fR
Do not load any initialization file\.
.
.TP
\fB\-o, \-\-output\fR \fIformat\fR
Output match data according to \fBformat\fR, which may be one of:
.
.IP
color, subs, matches, json, line
.
.IP
or possibly other (installation\-dependent) values\. Use \fBrosie help\fR to discover what is available in your installation\.
.
.IP
Note the default output style for the \fBmatch\fR command is \fBcolor\fR, and for the \fBgrep\fR command, is \fBline\fR\.
.
.TP
\fB\-\-rcfile\fR \fIfile\fR
Load the initialization file specified, instead of the default, \fB~/\.rosierc\fR\.
.
.TP
\fB\-\-rpl\fR \fIsource\fR
Define additional patterns, import additional packages\. The argument passed to \fB\-\-rpl\fR is typically enclosed in single quotes so that Rosie will see it as a single string with no shell expansions performed\.
.
.TP
\fB\-\-verbose\fR
When appropriate, output additional information\.
.
.SH "COMMAND OPTIONS"
.
.TP
\fB\-h, \-\-help\fR
Display help for a command\. This option must be given after the command name, e\.g\. \fBrosie match \-h\fR\.
.
.TP
\fB\-a, \-\-all\fR
Generate output for all input lines\. Lines that do not match the pattern are written to stderr, while matched output is written to stdout\.
.
.TP
\fB\-w, \-\-wholefile\fR
Match against the whole input file as if it were a single string\.
.
.TP
\fB\-F, \-\-fixed\-strings\fR
Interpret \fIpattern\fR as a set of fixed (literal) strings, instead of an RPL pattern (which reqires double quotes around string literals)\.
.
.TP
\fB\-\fR
Stop reading from the given input files, if any, and start reading from the standard input\.
.
.SH "ENVIRONMENT"
Currently, Rosie does not use any environment variables\. If this would be a useful addition, please open an issue on Rosie\'s GitHub repository to request this enhancement\.
.
.SH "FILES"
.
.TP
\fB~/\.rosierc\fR
This is the default initialization file, which is loaded before any command line options are processed\. The syntax of a Rosie rcfile is essentially the RPL syntax, with two dashes to start comments, and option values in double\-quoted strings\.
.
.IP
Options are set using an assignment\-like syntax, e\.g\.
.
.IP
\fBlibpath = "bar:baz"\fR
.
.IP
to set the rosie \fBlibpath\fR to a sequence of two directories, \fBbar\fR and \fBbaz\fR\.
.
.IP
The recognized options are:
.
.IP
\fBcolors\fR=\fIcolorspec\fR to set \fBcolors\fR to a \fIcolorspec\fR (can be used multiple times; values will be concatenated)
.
.IP
\fBlibpath\fR=\fIpaths\fR to set \fBlibpath\fR (can be used multiple times; values will be concatenated)
.
.IP
\fBloadfile\fR=\fIfile\fR to load the specified file (can be used multiple times to load multiple rpl files)
.
.SH "EXAMPLES"
Forthcoming
.
.SH "BUGS"
Rosie does not normalize Unicode input\. If a pattern contains composed characters, for example, these will not match their decomposed equivalents in the input (and vice versa)\.
.
.P
The RPL compiler is slow (but matching is reasonably fast)\.
.
.P
Issues (bugs and enhancement requests) may be found on the Rosie issue page \fIhttps://github\.com/jamiejennings/rosie\-pattern\-language/issues\fR\.
.
.SH "SEE ALSO"
See Rosie\'s home \fIhttp://rosie\-lang\.org\fR for news, docs, etc\.
.
.SH "AUTHOR"
Jamie A\. Jennings
.
.P
With contributions from the people listed in the CONTRIBUTORS \fIhttps://github\.com/jamiejennings/rosie\-pattern\-language/blob/master/CONTRIBUTORS\fR file\.
.
.P
Email the Rosie Project at \fIinfo@rosie\-lang\.org\fR\.
.
.P
Follow @jamietheriveter \fIhttps://twitter\.com/jamietheriveter\fR on Twitter\.
