#!/usr/bin/env bash

if [[ -z "${1}" ]]; then
    echo "Error: missing required first argument (Rosie installation directory)"
    echo "Note that this argument, while required, will be ignored if \$ROSIE_HOME is set"
    exit -1
fi

if [[ -n "${ROSIE_HOME}" ]]; then
    # echo ROSIE_HOME is: ${ROSIE_HOME}
    # echo Ignoring first arg, whose value is: ${1}
    home=${ROSIE_HOME}
else
    # echo ROSIE_HOME is empty
    # echo Using first arg, whose value is: ${1}
    home=${1}
fi

ROSIE_SCRIPT_HOME="${1}"
shift
executable="${home}/bin/lua"
cmd="$(ps -o args= $PPID)"

#echo Testing to see if ${home} is a Rosie installation directory
if [[ ! -d "${home}" ]]; then
    echo Error: ${home} is not a directory
    if [[ -z ${ROSIE_HOME} ]]; then
	echo "This value is named in the executable script that launches rosie,"
	echo "and an invalid value suggests the rosie installation failed."
	echo "Try uninstalling and reinstalling rosie."
    else
	echo "This directory is the value of the environment variable \$ROSIE_HOME,"
	echo "which should point to a rosie installation."
	echo "Try 'unset ROSIE_HOME' to use the default system installation of rosie."
    fi
    exit -1
elif [[ ! -x "${executable}" ]]; then
    echo Error: ${executable} not found or not executable
    exit -1
fi

#
# -D is an 'undocumented' command line option that launches Rosie in development mode
#
i=""
dev="false"
if [[ "$1" = "-D" ]]; then
   i="-i"
   dev="true"
   shift
fi

export ROSIE_HOME
export ROSIE_SCRIPT_HOME
export HOSTNAME
export HOSTTYPE
export OSTYPE
export CWD=`pwd`

# Lua's "long string" syntax [[...]] is needed because command line args could contain single and/or double quotes
${executable} $i -e "ROSIE_HOME=[[${home}]]; SCRIPTNAME=[[${cmd}]]; ROSIE_DEV=[[${dev}]];" -- "${home}/src/run.lua" "$@"


